dist: trusty
sudo: required
services:
  - docker

branches:
  only:
    - master
    - /^release\-.+/

script:
  - mntdir='/mnt/ocs-manager'
  - docker run --rm -v $(pwd):${mntdir} ubuntu:14.04 /bin/bash -c "sh ${mntdir}/scripts/package.sh ci_appimage"
  - cat transfer.log
